### ISSUE TITLE
App crashes on android 4.4.2

### ISSUE THREAD

**Issue by jonathancarrasco** [DJI-Mobile-SDK-Tutorials/Android-GSDemo-GoogleMap#10]
The demo application crashes while booting up on android 4.4.2 with the dji SDK 4.1.1 leaving the following crash report on android studio 2.3.2
06-14 19:45:55.159 15731-15731/com.dji.GSDemo.GoogleMap E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.dji.GSDemo.GoogleMap, PID: 15731
                                                                          java.lang.UnsatisfiedLinkError: Native method not found: dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString:()Ljava/lang/String;
                                                                              at dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString(Native Method)
                                                                              at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source)
                                                                              at com.dji.GSDemo.GoogleMap.DJIDemoApplication.onCreate(DJIDemoApplication.java:40)
                                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5154)
                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:156)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1418)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:157)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5872)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
                                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by dji-dev** [comment]
Will go ahead and close this ticket as current sdk version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
